services:
  web:
    build: .
    command: ["python", "manage.py", "runserver"]
    volumes:
      - ./app:/booksApp/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - booksonly-data:/var/lib/postgres/data/
    env_file:
      - ./.env

volumes:
  booksonly-data: