services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - booksonly-data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=ronny
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=booksonly


volumes:
  booksonly-data: