services:
  web:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

  
  db:
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - booksonly-data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=ronny
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=booksonly


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    env_file:
      - ~/sil-tasks/.env

volumes:
  booksonly-data:
  prometheus_data:
  grafana_data: