global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics'  # Django-prometheus exports metrics here

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

# Alert rules for monitoring
rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'