groups:
  - name: django_alerts
    rules:
      # HTTP Request Latency
      - alert: HighRequestLatency
        expr: rate(django_http_requests_latency_seconds_sum[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High request latency detected"
          description: "Request latency is above 1s"

      # Database Connections
      - alert: HighDatabaseConnections
        expr: django_db_new_connections_total > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of database connections"
          description: "More than 100 new database connections in 5 minutes"

      # HTTP Error Rate
      - alert: HighErrorRate
        expr: rate(django_http_responses_total_by_status_total{status=~"5.*"}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "More than 10% of requests are resulting in 5xx errors"