---
- name: Copy config file to the server
  hosts: server
  become: true

  tasks:
  - name: Create Devops Group
    group:
      name: devops
      state: present

  - name: Add user to Devops Group
    user:
      name: ubuntu
      append: true
      groups: devops

  - name: Copy the config.txt file to the server
    copy:
      src: config.txt
      group: devops
      mode: 0060
      dest: /opt/config.txt

- name: Configure Postgresql
  hosts: server
  become: true

  tasks:
  - name: Install Postgresql
    apt:
      name: postgresql
      state: latest
      update_cache: true

  - name: Enable and Run Postgres Service
    service:
      name: postgresql
      enabled: true
      state: started

- name: Configure Nginx
  hosts: server
  become: true

  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: latest
      update_cache: true

  - name: Enable and Run Nginx Service
    service:
      name: nginx
      enabled: true
      state: reloaded
